use tasq;
#set names cp1251;

DROP TABLE IF EXISTS tasq_tstatus;
CREATE TABLE tasq_tstatus (
	id				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	date_updated	TIMESTAMP(14),
	date_created	TIMESTAMP(14),
	date_published	TIMESTAMP(14),
	published		TINYINT UNSIGNED NOT NULL DEFAULT 0,
	deleted			TINYINT UNSIGNED NOT NULL DEFAULT 0,
	manorder		INTEGER UNSIGNED NOT NULL DEFAULT 0,
	ident			VARCHAR(250) NOT NULL DEFAULT '',

	hashkey			VARCHAR(250) NOT NULL DEFAULT '',

	PRIMARY KEY(id)
);

#desc tasq_tstatus;
#insert into tasq_tstatus(id, ident) values(1, 'NONE');

INSERT INTO tasq_tstatus (id, date_updated, date_created, date_published, published, deleted, manorder, ident, hashkey) VALUES
	(1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,1,'статус неизвестен','UNKNOWN'),
	(2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,2,'задача не сформулирована','NOT_STATED'),
	(7,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,3,'частично сформулирована','PARTIALLY_STATED'),
	(3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,4,'полностью сформулирована','FULLY_STATED'),
	(4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,5,'отправлена на выполнение','SUBMITTED'),
	(5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,6,'не достаточно деталей','NOT_ENOUGH_DETAILS'),
	(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,7,'полностью ясно как делать','CLEAR_FOR_DEVELOPMENT'),
	(8,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,8,'в разработке','UNDER_DEVELOPMENT'),
	(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,9,'готова демо-версия','DEMO_READY'),
	(11,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,10,'ожидает тестирования заказчиком','WAITING_FOR_CUSTOMER_TESTING'),
	(10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,11,'имеются замечания к демо','DEMO_HAS_FLAWS'),
	(12,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,12,'демо полностью устраивает','DEMO_APPROVED'),
	(13,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,13,'введено в эксплуатацию','LAUNCHED_taskION'),
	(14,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,14,'идея переродилась в другую','SELECT'),
	(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,15,'заказчик не требует выполнения','CUSTOMER_NOTPUSHING'),
	(16,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,16,'разработчик не хочет выполнять','DEVELOPER_LAZY'),
	(17,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,17,'идея безумна','CRAZY'),
	(18,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0,18,'усилия не оправданы','TOO_EXPENSIVE');

#select * from tasq_tstatus;